services:
  db:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    container_name: db
    networks:
      - my-network
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=landmark

  app:
    build: .
    ports:
      - "8080:8080"
    container_name: app
    networks:
      - my-network
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/landmark
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin

networks:
  my-network:
    driver: bridge